---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lipeng.
--- DateTime: 2021/4/19 10:30
---

--print("hello world")

--ngx.say("<p>hello world idea</p>")


local function main()
   ngx.say("Hello World111")
end

-- add replace incr get_keys get_stale
local function get_from_cache(key)
   local my_cache = ngx.shared.my_cache
   local value = my_cache:get(key)
   return value
end

main()